project_identifier: wirecom
base_path: .

files:
  -
    source: '/app/translations/account.pot'
    translation: '/app/translations/%two_letters_code%/LC_MESSAGES/messages.po'
    update_option: 'update_as_unapproved'
