name: Test Pull Request
on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        DISTRIBUTION: ["wire", "$DISTRIBUTION_0"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Yarn cache
        uses: c-hive/gha-yarn-cache@v1
        
      - name: Install JS dependencies
        run: yarn --frozen-lockfile
        env:
          DISTRIBUTION: ${{matrix.DISTRIBUTION}}
        
      - name: Test
        run: yarn test
